OasisLMF/ODS_Tools

ods_tools/oed/setting_schema.py, requirements.in
* Switching the version type to string needed an update to the version comparison 
PASS: https://github.com/OasisLMF/OasisPlatform/actions/runs/4427683548/jobs/7765672717
=> Fix version check

.github/workflows/test-platform.yml
* Run the platform unit tests on ods-tools pull requests
=> Add Platform testing to ODS-tools github actions

ods_tools/main.py, ods_tools/oed/setting_schema.py
* Added settings validation to `ods_tools` command line 
* Fixed bug in settings compatibility, where original key is removed.
=> Fix Settings compatibility for older workers 

.github/workflows/test-oasislmf.yml, .github/workflows/test-platform.yml, CHANGELOG.rst, ods_tools/__init__.py, ods_tools/main.py, ods_tools/oed/setting_schema.py, ods_tools/oed/source.py, ods_tools/oed/validator.py, tests/test_ods_package.py
* [#42](https://github.com/OasisLMF/ODS_Tools/pull/43) - ods_tools check crashes on empty location file
* [#35](https://github.com/OasisLMF/ODS_Tools/pull/36) - Bug in Analysis settings compatibility map 
* [#31](https://github.com/OasisLMF/ODS_Tools/pull/31) - Add Platform testing to ODS-tools github actions
=> Release 3.0.7 - for oasislmf 1.27

.github/workflows/test-oasislmf.yml, .github/workflows/test-platform.yml, .github/workflows/test.yml
=> Add lot3 package to CI 

ods_tools/oed/common.py, ods_tools/oed/oed_schema.py, ods_tools/oed/source.py, ods_tools/oed/validator.py, setup.py, tests/test_ods_package.py
=> add check for conditional requirement

.github/workflows/publish.yml, .github/workflows/test-oasislmf.yml, .github/workflows/test-platform.yml, CONTRIBUTING.md, README.md, tests/test_ods_package.py
=> Update CI for stable 3.0.x

.github/workflows/publish.yml, CHANGELOG.rst, ods_tools/__init__.py, ods_tools/data/analysis_settings_schema.json, ods_tools/data/model_settings_schema.json, ods_tools/oed/source.py, ods_tools/oed/validator.py, tests/test_ods_package.py
=> Release 3.1.1 (staging)

CHANGELOG.rst, ods_tools/__init__.py, ods_tools/data/analysis_settings_schema.json
=> Release 3.1.2

.github/workflows/build.yml, .github/workflows/test.yml, CHANGELOG.rst, ods_tools/__init__.py, ods_tools/data/model_settings_schema.json, ods_tools/main.py, ods_tools/oed/__init__.py, ods_tools/oed/common.py, ods_tools/oed/exposure.py, ods_tools/oed/forex.py, ods_tools/oed/oed_schema.py, ods_tools/oed/source.py, requirements.in, setup.py, tests/test_ods_package.py
* [#64](https://github.com/OasisLMF/ODS_Tools/pull/66) - Backward compatibility when adding new codes in OED
* [#68](https://github.com/OasisLMF/ODS_Tools/pull/69) - Define relationships between event and footprint sets
* [#70](https://github.com/OasisLMF/ODS_Tools/pull/70) - Fix/forex case error
* [#73](https://github.com/OasisLMF/ODS_Tools/pull/73) - Feature/peril filter
=> Release 3.1.3

CHANGELOG.rst, ods_tools/__init__.py, ods_tools/data/analysis_settings_schema.json, ods_tools/data/model_settings_schema.json, tests/test_ods_package.py
* https://github.com/OasisLMF/ODS_Tools/pull/77 
* https://github.com/OasisLMF/ODS_Tools/pull/80
=> Release 3.1.4

ods_tools/data/model_settings_schema.json
=> Update model_settings_schema.json allowing additional properties for additional_assets  #82

.github/workflows/publish.yml, .github/workflows/test-platform.yml, .github/workflows/test.yml
* Fixed default branches for platform testing and OasisDataManager
* Removed GPG package signing (feature removed from pypi)
=> Fix CI workflow default branches

CHANGELOG.rst, ods_tools/__init__.py, ods_tools/data/analysis_settings_schema.json
* https://github.com/OasisLMF/ODS_Tools/pull/91
=> Release 3.2.1

README.md
Updated the README.md file with instructions on how to use the "transform" command.
=> add transform to README.md

ods_tools/data/model_settings_schema.json
Fixes #105 
Moved correlation settings from root of model settings schema to inside model settings section.
=> updated model settings

setup.py
From release https://github.com/OasisLMF/ODS_OpenExposureData/releases/tag/3.2.0
=> Update OED spec to 3.2.0

CHANGELOG.rst, ods_tools/__init__.py, ods_tools/oed/__init__.py, ods_tools/oed/common.py, ods_tools/oed/exposure.py, ods_tools/oed/oed_schema.py, ods_tools/oed/source.py, ods_tools/oed/validator.py, tests/test_ods_package.py
* https://github.com/OasisLMF/ODS_Tools/pull/115
* https://github.com/OasisLMF/ODS_Tools/pull/117
=> Release 3.1.5 (30th May 2024)

ods_tools/data/analysis_settings_schema.json
#118                                                                
updated analysis settings correlation values to align with model settings values
from
- correlation_value
to
- hazard_correlation_value
- damage_correlation_value
=> correlation settings update

setup.py
Use OED schema from https://github.com/OasisLMF/ODS_OpenExposureData/releases/tag/3.4.0
=> Set OED schema to 3.4.0

ods_tools/data/model_settings_schema.json
closes #105                                                                    
hazard_correlation_value and damage_correlation_value added to model settings schema
=> correlation in model settings

ods_tools/oed/source.py, ods_tools/oed/validator.py
Updated validator to work with both v3 spec and v4 (implied allowed blanks).
=> Fix allow blank errors with OED v4 spec

CHANGELOG.rst, README.md, ods_tools/__init__.py, ods_tools/data/model_settings_schema.json, ods_tools/odtf/mapping/file.py, ods_tools/oed/source.py, ods_tools/oed/validator.py, tests/mapping_test.yaml, tests/t_input.csv, tests/test_ods_package.py
* https://github.com/OasisLMF/ODS_Tools/pull/130
* https://github.com/OasisLMF/ODS_Tools/pull/127
* https://github.com/OasisLMF/ODS_Tools/pull/132
* https://github.com/OasisLMF/ODS_Tools/pull/128
* https://github.com/OasisLMF/ODS_Tools/pull/133
=> Release 3.2.6 (July 31) 

.github/workflows/project-PR.yml, .github/workflows/project-issue.yml
=> Only run attach project issues workflow from Our repo - not forks

.github/workflows/build.yml, .github/workflows/publish.yml, .github/workflows/test-oasislmf.yml, .github/workflows/test.yml
=> Update GH actions artifacts to v4

ods_tools/data/analysis_settings_schema.json, ods_tools/data/model_settings_schema.json
=> Add disaggregation-flag

CHANGELOG.rst, ods_tools/__init__.py, ods_tools/data/model_settings_schema.json, ods_tools/odtf/mapping/base.py, ods_tools/oed/source.py, setup.py, tests/test_ods_package.py
* https://github.com/OasisLMF/ODS_Tools/pull/147
* https://github.com/OasisLMF/ODS_Tools/pull/157
* https://github.com/OasisLMF/ODS_OpenExposureData/pull/228
~~Updated OED spec to https://github.com/OasisLMF/ODS_OpenExposureData/pull/223~~
=> Release 3.2.8

setup.py
Fixed setup.py so the package build adds all files under `odtf/data/*`
=> test pkg build including all files under odtf/data

CHANGELOG.rst, ods_tools/__init__.py, ods_tools/data/analysis_settings_schema.json, ods_tools/data/model_settings_schema.json, setup.py
* https://github.com/OasisLMF/ODS_Tools/pull/162
* https://github.com/OasisLMF/ODS_Tools/pull/165
=> Release 3.2.9

ods_tools/data/analysis_settings_schema.json, ods_tools/data/model_settings_schema.json
Match schema default to the oasislmf package
=> Fix default for do_disaggregation to true

requirements.in
Fixes https://github.com/OasisLMF/ODS_Tools/issues/175
=> set min pin for jsonschema

.github/workflows/test.yml, setup.py
=> Drop testing for py3.8

ods_tools/data/model_settings_schema.json
=> Fixed Misleading description for numeric_parameters 

CHANGELOG.rst, ods_tools/__init__.py, ods_tools/oed/source.py, ods_tools/oed/validator.py, requirements.in, tests/requirements.in, tests/test_ods_package.py
###Release 4.0.3 
* https://github.com/OasisLMF/ODS_Tools/pull/192
* https://github.com/OasisLMF/ODS_Tools/pull/193
* https://github.com/OasisLMF/ODS_Tools/pull/196
=> Release 4.0.3
