OasisLMF/ODS_Tools

ods_tools/oed/validator.py
Parquet Can use None for blank value, add it to the set with np.nan and ''
=> add None to the set of Blank values

ods_tools/data/analysis_settings_schema.json, ods_tools/data/model_settings_schema.json, ods_tools/oed/setting_schema.py, requirements.in
* Fix #12 load settings file now return data using [jsonref](https://github.com/gazpachoking/jsonref) which automatic de-references [JSON Reference](https://datatracker.ietf.org/doc/html/draft-pbryan-zyp-json-ref-03) objects
* Switched settings `version` field type to string
=> Load setting schema files using jsonref

ods_tools/oed/source.py, tests/test_ods_package.py
Use the Stream object attributes to try and detected the data type stored. (csv, parquet, compressed, or csv)
=> detect stream_obj type if not set

ods_tools/oed/validator.py
=> only check non BLANK value in peril, occupancy, and construction code validation

ods_tools/__init__.py, ods_tools/main.py, ods_tools/oed/validator.py
in the main.py module the logger selected to be setup was ods_tools.main.
therefore none of the logger call in ods_tools.oed are inheriting from it.
change to use ods_tools logger instead
=> use the package logger instead of __name__ logger to setup handler and log level in main

ods_tools/oed/common.py, ods_tools/oed/oed_schema.py, tests/test_ods_package.py
Often exposure data are presented with extra blank character at the beginning or end of column name creating error if the column is required or silently ignoring the issue which could lead to invalid result.
This PR will strip the column name of extra blank to match correctly with OED field name.
It will also raise an error instead of simply logging the issue if a column is not recognized.
=> ignore extra blank in column name, raise error for invalid column name

setup.py
* Dynamically build all sub-dirs of `ods_tools` into pip package
**Note:** this PR is needed for https://github.com/OasisLMF/ODS_Tools/pull/37
```
In [y]: setuptools.find_packages(exclude=('tests', 'tests.*', 'tests.*.*'))
Out[y]: 
['ods_tools',
'ods_tools.oed',
'ods_tools.oed.required_fields',
'ods_tools.oed.required_fields.enums']
```
=> Replace hardcoded packages, with find_packages

ods_tools/oed/source.py
when check if categorical this error can appear
packages/ods_tools/oed/source.py", line 330, in prepare_df
elif df[col].dtype == 'category':
TypeError: data type 'category' not understood
using dtype name solve the issue
=> fix check category

ods_tools/oed/__init__.py, ods_tools/oed/common.py, ods_tools/oed/exposure.py, ods_tools/oed/source.py, tests/test_ods_package.py
When saving Exposure, add the option to manage unknown columns individually via a dict or generally via a single constant
option available are in UnknownColumnSaveOption
IGNORE = 1
RENAME = 2
DELETE = 3
=> add option to manage unknown column when saving files

ods_tools/data/analysis_settings_schema.json, ods_tools/data/model_settings_schema.json
An optional `footprint_set` model setting has been added to allow for the selection of footprint file according to the file suffix, which acts as the identifier. This allows footprints to be stored in multiple files rather than in a single master file. This is related to OasisLMF PR https://github.com/OasisLMF/OasisLMF/pull/1352.
=> Add footprint file suffix options

ods_tools/oed/source.py, tests/test_ods_package.py
=> make string column are writable when reading from parquet

ods_tools/data/analysis_settings_schema.json
The following options have been added:
- `pla` (bool): enable/disable post loss amplification.
- `pla_secondary_factor` (float): set the secondary loss factor to apply to post loss amplification/reduction factors.
- `pla_uniform_factor` (float): set the uniform loss factor to apply across all losses.
=> Add options to enable/disable post loss amplification, and set secondary and uniform post loss amplification factors

ods_tools/data/model_settings_schema.json, ods_tools/oed/setting_schema.py
The rename of `group_fields` -> `damage_group_fields` can cause problems for OasisPlatform Servers where multiple model versions are running together.  
workers build from `1.15.x` and `1.23.x` required the older **group_fields** key, which fails validation without this PR.
=> Model_settings, allow additional properties under 'data_settings'

ods_tools/data/analysis_settings_schema.json
The `aalcalcmeanonly` ktools component calculates the overall average period loss, skipping the calculation of the standard deviation from this value. The following boolean fields have been introduced to the analysis settings file:
- `aalcalc_meanonly`: if true, output table in legacy format.
- `alt_meanonly`: if true, output table in ORD format.
=> Add fields for running aalcalcmeanonly ktools component

ods_tools/data/model_settings_schema.json
Allow dependency between event set and footprint files #68 
* Added `valid_footprint_ids` per event set section
=> Allow dependency between event set and footprint files

.github/workflows/publish.yml, CHANGELOG.rst, ods_tools/__init__.py, ods_tools/oed/forex.py, tests/test_ods_package.py
=> Release 3.0.8

ods_tools/data/analysis_settings_schema.json, ods_tools/data/model_settings_schema.json, tests/test_ods_package.py
* Added missing values `aalcalcmeanonly`, `alt_meanonly`, `alct_confidence` to **valid_metrics** sections in model_settings. 
* Added testing so missing values are caught next time.
=> Fix missing model settings valid metrics

ods_tools/data/analysis_settings_schema.json
Added fields used in PRs https://github.com/OasisLMF/OasisLMF/pull/1401 and https://github.com/OasisLMF/OasisLMF/pull/1406.
The fields are:
- correlation_settings: mirrors the one in model_settings;
- vulnerability_set: similarly to footprint_set, chooses specific vulnerability file by its extension;
=> Added fields to analysis settings schema

ods_tools/data/model_settings_schema.json
New option `model_run_mode` to select execution type when submitting a task (Generate Inputs / Losses) in the OasisPlatform
=> Added worker run_mode to model_settings

ods_tools/data/analysis_settings_schema.json, ods_tools/data/model_settings_schema.json
Added "vulnerability_replacements" and "vulnerability_adjustments" to the analysis settings schema. Added vulnerability_set to model settings schema.
Used in PR [#1415](https://github.com/OasisLMF/OasisLMF/pull/1415) and PR [#1426](https://github.com/OasisLMF/OasisLMF/pull/1426).
"vulnerability_replacements" can be either the path to a .csv file, or a dictionary containing the vulnerability_ids to replace (e.g. {"1": [[1,1,0.01],[1,2,0.02],...], "2": [[1,1,0.4],...]}.
"vulnerability_adjustments" should be a dictionary with vulnerability_ids as keys and adjustment factors as values (e.g. {"4": 1.1, "12": 0.895}.
=> Add vulnerability adjustments field to schema

ods_tools/data/analysis_settings_schema.json
As `fmpy` can support concurrent net and gross reinsurance output streams, it becomes possible for the user to request output at intermediate inuring priorities. The following field has been added to facilitate this:
- `ri_inuring_priorities` (array of integers): values correspond to inuring priorities for which output is desired, e.g. `[1]`, `[1, 3, 4]`, etc.
=> Add ri_inuring_priorities field to analysis settings schema for outputs at intermediate inuring priorities

.github/workflows/test.yml
Resolve testing failure `ERROR: No matching distribution found for fsspec>=2023.12.2` by ditching p3.7 checks
=> CI update - replace py3.7 with py3.11

ods_tools/oed/oed_schema.py
Allow the method of OedSchema peril_filtering to also check if a peril group (peril that represent multiple sub perils) is included in peril_filters.
Previously only sub_perils could be valid
this new behavior is piloted by include_sub_group:
if False: # historical behavior
WTC is valid for WW1
WW1 is not  valid for WW1
WW1 is not  valid for AA1
AA1 is not valid for WW1
if True: # new behavior
WTC is valid for WW1
WW1 is  valid for WW1
WW1 is valid for AA1
AA1 is not valid for WW1
note:
In OasisLMF this allow models to return a peril group as a key instead of imposing them to only use sub perils
=> include peril group as valid when doing peril filtering

ods_tools/odtf/data/mappings/mapping_loc_Cede-OED.yaml
`WallSidingCode` information is now correctly stored in the `Cladding` column when converting Cede to OED (and vice versa)
0 to 7 maps directly, whatever value above 7 in the conversion OED->Cede is assigned value 0 (unknown).
=> Update cede mappings (cladding)

ods_tools/oed/source.py, tests/test_ods_package.py
UseReinsDates is a string column with a default, this case was not handled well when loading ri_info
=> fix issue when categorical column have a default value

ods_tools/data/model_settings_schema.json, tests/test_ods_package.py
Fixed https://github.com/OasisLMF/ODS_Tools/issues/3  the option `ord_output` is a grouping of output types and not itself a metric, removed from `valid_metrics` options to avoid confusion
=> Removed 'ord_output' from valid_metrics in model-settings

ods_tools/data/analysis_settings_schema.json
With the feature https://github.com/OasisLMF/OasisLMF/pull/1482 more than 9 summary groups are now supported.
=> Remove summary groups max value

CHANGELOG.rst, ods_tools/__init__.py, ods_tools/data/analysis_settings_schema.json, ods_tools/data/model_settings_schema.json, ods_tools/odtf/data/mappings/mapping_loc_Cede-OED.yaml, ods_tools/oed/__init__.py, ods_tools/oed/common.py, ods_tools/oed/exposure.py, ods_tools/oed/oed_schema.py, ods_tools/oed/source.py, ods_tools/oed/validator.py, setup.py, tests/test_ods_package.py
* https://github.com/OasisLMF/ODS_Tools/pull/109
* https://github.com/OasisLMF/ODS_Tools/pull/108
* https://github.com/OasisLMF/ODS_Tools/pull/115
* https://github.com/OasisLMF/ODS_Tools/pull/111
* https://github.com/OasisLMF/ODS_Tools/pull/113
* https://github.com/OasisLMF/ODS_Tools/pull/117
=> Release 3.2.4 (30th May 2024)

ods_tools/data/analysis_settings_schema.json
linked to https://github.com/OasisLMF/OasisLMF/pull/1517                                                                              
additional support for ranges of event ids in analysis schema.
new field "event ranges" (string) with format "1-4,8,84-98"
can be used in combination with existing event id array
=> event ranges

ods_tools/main.py, ods_tools/odtf/controller.py, ods_tools/odtf/data/mappings/mapping_loc_Cede-OED.yaml
A simple transformation from air to oed and vice versa can be run without creating a config file, but simply by command line
It is now possible to run a transformation without using a configuration file. Solves #125.
For example, the command:
`ods_tools transform --format air-oed --input-file air_input.csv --output-file oed_output.csv`
will produce the oed file `output.csv` from the air file `input.csv`
We currently support `air-oed` and `oed-air`.
=> Transform air-oed without config file

tests/test_ods_package.py
For example `ContentsTIV` is now an optional field, so won't be automatically added with its default value populated
=> Update test for OED4 - test_field_required_allow_blank

requirements-extra.in, tests/requirements.in
While testing the solution, lark is pinned to a working version to avoid failing tests.
=> pin lark version

ods_tools/odtf/transformers/transform.py, requirements-extra.in, tests/requirements.in, tests/t_input.csv, tests/test_ods_package.py
Compatibility with all lark versions
Solves #140.
Removes the need for pinning lark to <= 1.1.9 in ods-tools requirements and ods-tools test requirements.
=> Fix issue with lark 1.1.9

ods_tools/data/model_settings_schema.json
There are two locations of `correlation_settings` one is **Legacy** which at the root of the file. The new version is within the `model_settings` attribute (fixed the description field to avoid confusion
=> Both correlation_settings fields are marked as "Legacy" in desc

setup.py
The validation now uses the v4.0.0 version of OED. 
For more details on OED v4 see the [release notes](https://github.com/OasisLMF/ODS_OpenExposureData/releases/tag/4.0.0)
=> Update OED schema to release v4

.github/workflows/build.yml
=> CI Fix - branches renamed in OED repo

ods_tools/data/model_settings_schema.json
Fix for https://github.com/OasisLMF/ODS_Tools/issues/177  - schema is functionally the name 
Note: when built into the Platform OpenAPI schema,  all references are 'unrolled' within the `model_settings` and `analyses_settings` schemas. 
The result looks like: 
[test-schema.json](https://github.com/user-attachments/files/18981866/test-schema.json)
=> Adjust model settings schema, replace AllOf with schema refs

setup.py
=> drop py3.8 testing but don't force the version
